__version__ = '1.0.1' # Dev version
#__version__ = '1.0.0' # start of dorkylever-version
#__version__ = '0.9.100'  # Perm stats config key checker
# __version__ = '0.9.94'  # Perm stats bug with short_name column where there are empty values
# __version__ = '0.9.93'  #  Minor chnage on perm stats config. Output dir now has deafult to cfg dir
#__version__ = '0.9.92'  # git log problem fixed
# __version__ = '0.9.91' # Fixed organ vol plots so not dependent on how paths are entered in config
# __version__ = '0.9.90' # Permutation stats now create null distributon per label. As QC can lead to difference data structure per label
#__version__ = '0.9.83' # Fixed a a couple of minor stats bugs
#__version__ = '0.9.82'
#__version__ = '0.9.81' # Fixed stats InvertHeatemap bug
#__version__ = '0.9.80'
