ELX_TRANSFORM_NAME = 'TransformParameters.0.txt'
ELX_PARAM_PREFIX = 'elastix_params_'
ELX_INVERTED_POINTS_NAME = 'outputpoints.vtk'
FILE_FORMAT = '.nrrd'
LOG_FILE = 'inversion.log'
TRANSFORMIX_OUT_NAME = 'result.nrrd'
INVERSION_DIR_NAME = 'Inverted_transform_parameters'
LABEL_INVERTED_TRANFORM = 'labelInvertedTransform.txt'
IMAGE_INVERTED_TRANSFORM = 'ImageInvertedTransform.txt'
VOLUME_CALCULATIONS_FILENAME = "organvolumes.csv"
INVERT_CONFIG = 'invert.yaml'
REG_DIR_ORDER_CFG = 'reg_order.txt'
RESOLUTION_IMGS_DIR = 'resolution_images'  # When reading images from dir and subdirs, ignore images in this folder
TRANSFORMIX_OUT = 'result.nrrd'  # This will not be correct if filetype is not nrrd
IMG_PYRAMID_DIR = 'pyramid_images'