# This is the new (281118) stats config for the standard stats pipeline

stats_types = [
'intensity',
'jacobians',
'organ_volumes'
]

# This is the final folder in the registration sheme
reg_folder = 'deformable_6'
# The final Jacobian determinat folder
jac_folder = '160_to_6'

# Tight mask for restricting the analysis to
mask = 'stats_mask.nrrd'
label_info = 'E14_5_atlas_v24_43_label_info.csv'
label_map = '210713_C3H_atlas_n18.nrrd'
blur_fwhm = 100
voxel_size = 40.0 #this may need changing
invert_stats = false

# Linearly normalise intensity data to th mean intensity withing the mask
normalise = 'histogram'

# Have whole embryo volume in the linear model to account for developmental substage
use_staging = true

# Enable Two-way study for interaction effects
two_way = true
